spring:
  application:
    name: booklay-coupon

#  profiles:
#    active: dev

  config:
    import: "optional:configserver:http://133.186.218.11:8888"
  kafka:
    consumer:
      group-id: consumer
    bootstrap-servers: localhost:9092

message:
  topic:
    name: quickstart-events

server:
  port: 8090