spring:
  application:
    name: booklay-coupon


  config:
    import: "optional:configserver:http://133.186.218.11:8888"
  kafka:
    consumer:
      group-id: coupon-test

server:

  port: 8090

logging:
  level:
    root: debug



